meals/urls.py
from django.urls import path
from . import views

app_name = 'meals'

urlpatterns = [
    path('', views.meal_list, name='meal_list'),
    path('<slug:slug>', views.meal_detail, name='meal_detail')

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('meals/', include('meals.urls', namespace='meals')),
    path('reserve_table', include('reservation.urls', namespace='reservation'))
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('', views.reserve_table, name='reserve_tablet'),

]

meals/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.


class Meals(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=500)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True)
    people = models.IntegerField()
    price = models.DecimalField(max_digits=5, decimal_places=2)
    preparation_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True, null=True)

    
    
    def save(self , *args , **kwargs):
        if not self.slug and self.name :
            self.slug = slugify(self.name)
        super(Meals , self).save(*args, **kwargs)
    
    

    class Meta:
        verbose_name = 'meal'
        verbose_name_plural = 'meals'
        
    
    def __str__(self):
        return self.name

        
class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'



    def __str__(self):
        return self.name
    
    

reservation/models.py
from django.db import models

# Create your models here.

class Reservation(models.Model):

    name = models.CharField(max_length=30)
    email = models.EmailField()
    Phone = models.IntegerField()
    number_of_person = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()
    message = models.CharField(max_length=300)

    def __str__(self):
        return self.name

        

reservation/forms.py
from django import forms
from .models import Reservation


class ReserveTableForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = '__all__'

meals/views.py
from django.shortcuts import render

# Create your views here.
from .models import Meals


def meal_list(request):
    meal_list = Meals.objects.all()

    context = {'meal_list' : meal_list, }
    return render(request, 'Meals/list.html', context)

def meal_detail(request, slug):
    meal_detail = Meals.objects.get(slug=slug)

    context = {'meal_detail' : meal_detail}

    return render(request, 'Meals/detail.html', context)

reservation/views.py
from django.shortcuts import render
from .forms import ReserveTableForm
# Create your views here.

from reservation.models import Reservation

def reserve_table(request):

    context = {}

    return render(request, 'reservation/reservation.html', context)

meals/templates/Meals/detail.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
	

	<div class="gtco-section">
		<div class="gtco-container">
            <img class = "meal_img" src="{{meal_detail.image.url}}" alt="">
            <h2>{{meal_detail}}</h2>
            <p>{{meal_detail.description}}</p>

            <p>For :  {{meal_detail.people}} People</p>
            <p>Preparation time : {{meal_detail.preparation_time}} Minutes</p>
            <p>Price : {{meal_detail.price}} $ </p>
		</div>
	</div>
	
	

	{% endblock body %}

meals/templates/Meals/list.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
	

	<div class="gtco-section">
		<div class="gtco-container">
	
			<div class="row">
				{% for meal in meal_list %}
					<div class="col-lg-4 col-md-4 col-sm-6">
						<a href="{% static 'site_static/images/pilov.jpeg' %}" class="fh5co-card-item image-popup">
							<figure>
								<div class="overlay"><i class="ti-plus"></i></div>
								<img src="{{meal_detail.image.url}}" alt="Image" class="img-responsive">
							</figure>
							<div class="fh5co-text">
								<h2><a href="{% url 'meals:meal_detail' meal.slug%}">{{meal.name}}"></a></h2>
								<p>{{meal.description}}</p>
								<p><span class="price cursive-font">{{meal.price}}$</span></p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>

	

	{% endblock body %}

reservation/templates/reservation/reservation.html
<style>
  /*==================
RESERVATION SECTION
====================*/
#mu-reservation{
	background-color: #222;
	display: inline;
	float: left;
	padding: 100px 0;
	width: 100%;
	.mu-reservation-area{
		display: inline;
		float: left;
		width: 100%;
		.mu-title{
			h2{
				color: #fff;
			}
		}
		.mu-reservation-content{
			display: inline;
			float: left;
			margin-top: 20px;
			padding: 0 100px;
			width: 100%;			
			h3{
				color: #fff;
				display: inline-block;
				padding-bottom: 10px;
				font-weight: bold;
			}
			p{
				color: #fff;
				letter-spacing: 0.5px;
				padding: 0 50px;
				text-align: center;
			}
			.mu-reservation-form{
				margin-top: 30px;
				text-align: center;

				.form-control{
					margin-bottom: 20px;
				}

				input[type="text"],
				input[type="email"]{						
					border-radius: 0;
					color: #000;
					height: 40px;
					&:focus{
						box-shadow: none;
					}
					&::-webkit-input-placeholder {
					   color: #555;
					}

					&:-moz-placeholder { // Firefox 18-
					   color: #555;
					}

					&::-moz-placeholder {  // Firefox 19+
					  color: #555;  
					}

					&:-ms-input-placeholder {  
					   color: #555; 
					}
				}
				select{
					border-radius: 0;
					height: 40px;					
					&:focus{
						box-shadow: none;
					}
					option{
						margin-bottom: 10px;
						color: #000;
					}
				}
				textarea{
					border-radius: 0;
					color: #000;
					padding: 10px;
					&:focus{
						box-shadow: none;
					}
					&::-webkit-input-placeholder {
					   color: #555;
					}

					&:-moz-placeholder { // Firefox 18-
					   color: #555;
					}

					&::-moz-placeholder {  // Firefox 19+
					  color: #555;  
					}

					&:-ms-input-placeholder {  
					   color: #555; 
					}
				}
				button[type="submit"]{
					border: none;
					margin-top: 20px;
					margin-left: 15px;
				}
				
			}
		}
	}
}
.datepicker {
  border-radius: 0;					 
  padding: 6px 10px;
}
.datepicker .datepicker-switch, .datepicker .prev, .datepicker .next, .datepicker tfoot tr th { 
  font-size: 20px;
}
.table-condensed > thead > tr > th, .table-condensed > tbody > tr > th, .table-condensed > tfoot > tr > th, .table-condensed > thead > tr > td, .table-condensed > tbody > tr > td, .table-condensed > tfoot > tr > td {
  padding: 6px;
}
.datepicker table tr td.day:hover{	
	color: #fff;
}

</style>


<!-- Start Reservation section -->
<section id="mu-reservation">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="mu-reservation-area">
            <div class="mu-title">
              <span class="mu-subtitle">Make A</span>
              <h2>Reservation</h2>
              <i class="fa fa-spoon"></i>              
              <span class="mu-title-bar"></span>
            </div>
            <div class="mu-reservation-content">
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ratione quidem autem iusto, perspiciatis, amet, quaerat blanditiis ducimus eius recusandae nisi aut totam alias consectetur et.</p>
              <form class="mu-reservation-form">
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">                       
                      <input type="text" class="form-control" placeholder="Full Name">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">                        
                      <input type="email" class="form-control" placeholder="Email">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">                        
                      <input type="text" class="form-control" placeholder="Phone Number">
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <select class="form-control">
                        <option value="0">How Many?</option>
                        <option value="1 Person">1 Person</option>
                        <option value="2 People">2 People</option>
                        <option value="3 People">3 People</option>
                        <option value="4 People">4 People</option>
                        <option value="5 People">5 People</option>
                        <option value="6 People">6 People</option>
                        <option value="7 People">7 People</option>
                        <option value="8 People">8 People</option>
                        <option value="9 People">9 People</option>
                        <option value="10 People">10 People</option>
                      </select>                      
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <input type="text" class="form-control" id="datepicker" placeholder="Date">              
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Phone No">                      
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <textarea class="form-control" cols="30" rows="10" placeholder="Your Message"></textarea>
                    </div>
                  </div>
                  <button type="submit" class="mu-readmore-btn">Make Reservation</button>
                </div>
              </form>      
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>  
  <!-- End Reservation section -->

templates/base.html
{% load static %}

<!DOCTYPE HTML>
<!--
	Aesthetic by gettemplates.co
	Twitter: http://twitter.com/gettemplateco
	URL: http://gettemplates.co
-->
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Savory &mdash; Free Website Template, Free HTML5 Template by GetTemplates.co</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by GetTemplates.co" />
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive" />
	<meta name="author" content="GetTemplates.co" />

  	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'site_static/css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'site_static/css/icomoon.css' %}">
	<!-- Themify Icons-->
	<link rel="stylesheet" href="{% static 'site_static/css/themify-icons.css' %}">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'site_static/css/bootstrap.css' %}">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'site_static/css/magnific-popup.css' %}">

	<!-- Bootstrap DateTimePicker -->
	<link rel="stylesheet" href="{% static 'site_static/css/bootstrap-datetimepicker.min.css' %}">

	<!-- Owl Carousel  -->
	<link rel="stylesheet" href="{% static 'site_static/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'site_static/css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href="{% static 'site_static/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src="{% static 'site_static/js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
		
	<div class="gtco-loader"></div>
	
	<div id="page">

	
	<!-- <div class="page-inner"> -->
	<nav class="gtco-nav" role="navigation">
		<div class="gtco-container">
			
			<div class="row">
				<div class="col-sm-4 col-xs-12">
					<div id="gtco-logo"><a href="{% static 'site_static/index.html' %}">Savory <em>.</em></a></div>
				</div>
				<div class="col-xs-8 text-right menu-1">
					<ul>
						<li><a href="{% static 'site_static/menu.html' %}">Menu</a></li>
						<li class="has-dropdown">
							<a href="{% static 'site_static/services.html' %}">Services</a>
							<ul class="dropdown">
								<li><a href="#">Food Catering</a></li>
								<li><a href="#">Wedding Celebration</a></li>
								<li><a href="#">Birthday's Celebration</a></li>
							</ul>
						</li>
						<li><a href="{% static 'site_static/contact.html' %}">Contact</a></li>
						<li class="btn-cta"><a href="#"><span>Reservation</span></a></li>
					</ul>	
				</div>
			</div>
			
		</div>
	</nav>
	
	<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url({% static 'site_static/images/img_bg.jpeg' %})" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row">
				<div class="col-md-12 col-md-offset-0 text-left">
					

					<div class="row row-mt-15em">
						<div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp">
							<span class="intro-text-small">Hand-crafted by <a href="http://gettemplates.co" target="_blank">GetTemplates.co</a></span>
							<h1 class="cursive-font">All in good taste!</h1>	
						</div>
						<div class="col-md-4 col-md-push-1 animate-box" data-animate-effect="fadeInRight">
							<div class="form-wrap">
								<div class="tab">
									
									<div class="tab-content">
										<div class="tab-content-inner active" data-content="signup">
											<h3 class="cursive-font">Table Reservation</h3>
											<form action="#">
												<div class="row form-group">
													<div class="col-md-12">
														<label for="activities">Persons</label>
														<select name="#" id="activities" class="form-control">
															<option value="">Persons</option>
															<option value="">1</option>
															<option value="">2</option>
															<option value="">3</option>
															<option value="">4</option>
															<option value="">5+</option>
														</select>
													</div>
												</div>
												<div class="row form-group">
													<div class="col-md-12">
														<label for="date-start">Date</label>
														<input type="text" id="date" class="form-control">
													</div>
												</div>
												<div class="row form-group">
													<div class="col-md-12">
														<label for="date-start">Time</label>
														<input type="text" id="time" class="form-control">
													</div>
												</div>

												<div class="row form-group">
													<div class="col-md-12">
														<input type="submit" class="btn btn-primary btn-block" value="Reserve Now">
													</div>
												</div>
											</form>	
										</div>

										
									</div>
								</div>
							</div>
						</div>
					</div>
							
					
				</div>
			</div>
		</div>
	</header>

	{% block body %}

	{% endblock body %}
	


	<footer id="gtco-footer" role="contentinfo" style="background-image: url({% static 'site_static/images/img_bg.jpeg' %})" data-stellar-background-ratio="0.5">
		<div class="overlay"></div>
		<div class="gtco-container">
			<div class="row row-pb-md">

				

				
				<div class="col-md-12 text-center">
					<div class="gtco-widget">
						<h3>Get In Touch</h3>
						<ul class="gtco-quick-contact">
							<li><a href="#"><i class="icon-phone"></i> +1 234 567 890</a></li>
							<li><a href="#"><i class="icon-mail2"></i> info@GetTemplates.co</a></li>
							<li><a href="#"><i class="icon-chat"></i> Live Chat</a></li>
						</ul>
					</div>
					<div class="gtco-widget">
						<h3>Get Social</h3>
						<ul class="gtco-social-icons">
							<li><a href="#"><i class="icon-twitter"></i></a></li>
							<li><a href="#"><i class="icon-facebook"></i></a></li>
							<li><a href="#"><i class="icon-linkedin"></i></a></li>
							<li><a href="#"><i class="icon-dribbble"></i></a></li>
						</ul>
					</div>
				</div>

				<div class="col-md-12 text-center copyright">
					<p><small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small> 
						<small class="block">Designed by <a href="http://gettemplates.co/" target="_blank">GetTemplates.co</a> Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small></p>
				</div>

			</div>

			

		</div>
	</footer>
	<!-- </div> -->

	</div>

	<div class="gototop js-top">
		<a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
	</div>
	
	<!-- jQuery -->
	<script src="{% static 'site_static/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'site_static/js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'site_static/js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'site_static/js/jquery.waypoints.min.js' %}"></script>
	<!-- Carousel -->
	<script src="{% static 'site_static/js/owl.carousel.min.js' %}"></script>
	<!-- countTo -->
	<script src="{% static 'site_static/js/jquery.countTo.js' %}"></script>

	<!-- Stellar Parallax -->
	<script src="{% static 'site_static/js/jquery.stellar.min.js' %}"></script>

	<!-- Magnific Popup -->
	<script src="{% static 'site_static/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'site_static/js/magnific-popup-options.js' %}"></script>
	
	<script src="{% static 'site_static/js/moment.min.js' %}"></script>
	<script src="{% static 'site_static/js/bootstrap-datetimepicker.min.js' %}"></script>


	<!-- Main -->
	<script src="{% static 'site_static/js/main.js' %}"></script>

	</body>
</html>